///@desc creation stuff
thisNumber = depth;
depth = 0;
myHeroId = heroId[thisNumber]
preciseX = x;
preciseY = y;
ix = preciseX;
iy = preciseY;
hitbox = objIceLobHitbox;
angle = myHeroId.lobAngle;
spd = myHeroId.lobSpd;
dx = spd * dcos(angle) * myHeroId.image_xscale;
ddx = 0
dy = spd * dsin(angle);
ddy = myHeroId.lobDdy
smallXSpd = myHeroId.smallLobXSpd;
factor = myHeroId.lobFactor;
smallLobNumber = myHeroId.smallLobNumber
iTime = current_time
lastTime = current_time
xChange = 0
yChange = 0
tChange = 0