/// @desc creation stuff
dmg = punchDmg;
slowTime = punchSlowTime;
slowTo = punchSlowTo;
stunTime = punchStunTime;
controlScheme = monkControlScheme;
projId = id;
dot = false;
spd = 0;
var xDiff = mouse_x - x;
var yDiff = y - mouse_y;
var hyp = sqrt(xDiff * xDiff + yDiff * yDiff);
dx = spd * xDiff / hyp;
dy = spd * yDiff / hyp;
preciseX = x;
preciseY = y;
depth = -1;
image_speed = 1;
scrHeroId();
image_angle = heroId.mouseAngle;
alarm[0] = image_number;