///@desc creation stuff
thisNumber = depth;
depth = 0;
myHeroId = heroId[thisNumber];
dmg = 0;
dDmg = 0;
duration = 1;
forever = false;
slowTo = myHeroId.blastSlowTo;
dSlowTo = 0;
slowDuration = 1;
slowForever = false;
time = 1;
currTime = 0;